### ISSUE TITLE
[Bug] React课程，部分题目验证不通过

### ISSUE THREAD

**Issue by Jfreey** [freeCodeCamp-China/learn#25]
经过调试发现了一些问题，当前learn项目中yarn.lock采用的包是来自于cnpm，并且版本与英文版fcc的yarn.lock不同（有些包的版本要比英文版的版本高）,clone项目后最终使用英文原版的yarn.lock替换当前yarn.lock后，React部分题目提交正常，不会再报验证不通过的问题。希望考虑能与英文版同步包的版本，并且建议替换掉cnpm的taobao源，使用yarn的原始源，taobao的源在包的构建方面有些不稳定，有的时候一些莫名其妙的错误都来自于taobao源。

**Comment by ZhichengChen** [comment]
厉害厉害，试了一下，还真好了
